// Generated by https://quicktype.io

class NotificationResumeModel {
  String texto;
  String uid;
  String enviadopara;
  String tipo;
  String data;
  String enviadopor;
  String hora;
  String titulo;
  String arquivo;
  int id;
  String enviadoem;
  int listaId;

  NotificationResumeModel({
    this.texto,
    this.uid,
    this.enviadopara,
    this.tipo,
    this.data,
    this.enviadopor,
    this.hora,
    this.titulo,
    this.arquivo,
    this.id,
    this.enviadoem,
    this.listaId,
  });

  
  factory NotificationResumeModel.fromJson(Map<String, dynamic> parsedJson) {
    return NotificationResumeModel(
      texto: parsedJson['texto'],
      uid: parsedJson['uid'],
      enviadopara: parsedJson['enviadopara'],
      tipo: parsedJson['tipo'],
      data: parsedJson['data'],
      enviadopor: parsedJson['enviadopor'],
      hora: parsedJson['hora'],
      titulo: parsedJson['titulo'],
      arquivo: parsedJson['arquivo'],
      id: parsedJson['id'],
      enviadoem: parsedJson['enviadoem'],
      listaId: parsedJson['listaId'],
    );
  }
}
